version: '2'

linters:
  default: standard
  disable:
    - lll
    - unused
  settings:
    varnamelen:
      ignore-decls:
        - is *is.I
    wsl:
      allow-trailing-comment: true
  exclusions:
    generated: lax
    warn-unused: true
    presets:
      - std-error-handling

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt

  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(go.jlucktay.dev/adventofcode)
        - blank
        - dot
      no-inline-comments: true
      no-prefix-comments: true
      custom-order: true
      no-lex-order: false

    gofmt:
      simplify: true
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'

    gofumpt:
      extra-rules: true

  exclusions:
    generated: lax

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    tab:
      print-linter-name: true
      colors: true
  sort-order:
    - linter
    - file
  show-stats: true

run:
  tests: true
  modules-download-mode: readonly
