coverage:
  badge:
    path: docs/coverage.svg
  paths:
    - '**/cover.*.out'
codeToTestRatio:
  badge:
    path: docs/ratio.svg
  code:
    - '**/*.go'
    - '!**/*_test.go'
  test:
    - '**/*_test.go'
testExecutionTime:
  acceptable: 1min
  badge:
    path: docs/time.svg
  steps:
    # This step name is linked to the '.github/workflows/go.yaml' Actions file.
    - Run task to gather Go test coverage
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
body:
  if: is_pull_request
comment:
  if: is_pull_request
summary:
  if: true
report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}
push:
  if: true
  message: Update pushed by Octocov
