language: go

go:
  - "1.x"
  - "1.10.x"
  - master

jobs:
  include:
    - script: go test ./... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack:
    secure: Yw+njpf/ukBWzz0EUtcxfOixJNgCsMq/zXlkup2gURHH6TPVCpcol7InJSffRD9BdEAaZ2iJnJwoTij406KKuNtJ8sq2GVFmUe0dRBqnAo/MVsrCSWZ+mwqwMv/4jlOM+ZsWaEgqsVkIT8h+RmvSL0cCJP5IPpZCSPAw788lJcvtRTsut/Lj7LHp2vEkHo4BC38STaBwkzgurNNuTOJYVLfGZaw2piqOOaD5qDbEHgC/xJGgw/rn4YmnyFTqgbJyd1roD1NNote71RpTpfxnhKNCw0VhDbgNaN5FExkDobnyKruBVuU6LQW4JiEFm6PSQeQ8fNArgkD2MF+yVhOTSoDfyCN6tZK43Fv+kJRQ5qowWn29C1oppwt5uApyqKdnwq2v7AzgUtbs6mDSeBmg4cOIVaJefMJkBQfKhO6l/sVqUnR9KdIovmHYgQnfPYPZkvAI0lYgJPWfCpOSqfhGjCINxM+qbRJA04ak/W3VGRdaaxsf9yZjeYzBKcP4Zx1hRYkR2HyJ8gGETl+PRHVFgj+5T7ZbdLj/waxtJ5MSfVWEWd0ajeUF12iMz8YjOxHfXJ5YtIkFHlHcjboe7XAzx5c7TirfK0RdSmF1DvzFT3y8XOX5KzV7wrkq2nsWYoww6o5BgtBNbSOT4VgkNzW8xS3bN03VTgzVnOXMhQrNHpk=
