default: test build-run clean

test:
	go test -count=1000 -vet "" ./day*

testnewscanner:
	go test -count=1 -failfast -run '^TestNewScanner$' -v -vet "" ./day03

build-run:
	#!/usr/bin/env bash
	for day in day[0-9][0-9]; do
		go build -o "cmd-${day}" "./$day/cmd"
		echo "$day"
		"./cmd-${day}" "$day/input.txt"
		echo
	done

clean:
	rm -fv ./cmd-day[0-9][0-9]
